name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Force LF globally before checkout
        if: matrix.os == 'windows-latest'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
        shell: bash

      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true
      
      - name: Enable pnpm
        run: corepack enable pnpm

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pnpm install --frozen-lockfile

      - name: Install dependencies for fixtures
        run: |
          cd fixtures/demo
          pnpm install --frozen-lockfile
          cd ../../

      - name: Run tests on macOS
        if: matrix.os == 'macos-latest'
        uses: GabrielBB/xvfb-action@v1.7
        with:
          working-directory: ./
          run: pnpm run test

      - name: Run tests on Windows
        if: matrix.os == 'windows-latest'
        run: pnpm run test

