name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache
        with:
          path: '**/**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/setup-node@v4
        with:
          node-version: '14'
          check-latest: true

      - name: install yarn
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install yarn -g

      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install
          yarn global add npm-publish

      - name: Prettify code
        run: |
          echo "Prettifying code"
          yarn fix:prettier

      - name: install dependencies for fixtures
        run: |
          cd fixtures/demo
          yarn install
          cd ../../

      - name: gabrielbb/xvfb-action
        uses: GabrielBB/xvfb-action@v1.4
        with:
          working-directory: ./
          run: yarn test

      - name: publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./docs
          commit_message: '[ci skip] Updates'
